name: Terraform-Apply

on:
  push:
    branches: [ "master" ]
    
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
     AWS_REGION: 'us-east-1'
    
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Format
        id: fmt
        run: terraform fmt
    
      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        if: github.event_name == 'pull_request'
        run: terraform apply -auto-approve
